// <auto-generated />
namespace CommerceApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddShfit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShfit));
        
        string IMigrationMetadata.Id
        {
            get { return "201504060157149_AddShfit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
