// <auto-generated />
namespace CommerceApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class birth_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(birth_date));
        
        string IMigrationMetadata.Id
        {
            get { return "201505060332213_birth_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
